update to v2.05
intercept/intercept pull request #247
Opened 2021-04-28 00:03 UTC by Leopard20

Added many new commands and event handlers
I also fixed several event handlers and some commands

2021-04-28 03:00 UTC, Leopard20 commented on src/client/intercept/client/sqf/vehicles.cpp
> +        #define RETURN_PYLON_MAGS if (game_return.is_empty()) return sqf_return_string_list(); \
@dedmen plz review this

2021-04-28 10:39 UTC, dedmen commented on src/client/headers/client/eventhandlers.hpp
> +#define EH_Func_Args_Object_PathCalculated types::object agent, std::vector<types::vector3> path
auto_array would be the native engine one. In most cases i guess native is preferred.
But here we have to copy the values anyway so it doesn't make a difference

2021-04-28 10:40 UTC, dedmen commented on src/client/headers/client/eventhandlers.hpp
> +        types::r_string text_lb{};
put the strings together and the float at end.
strings are x64bit and float is 32bit. Better have the padding at end instead of in the middle

2021-04-28 10:41 UTC, dedmen commented on src/client/headers/client/eventhandlers.hpp
> +#define EH_Func_Args_Object_PathCalculated types::object agent, std::vector<types::vector3> path
you used auto_array in EH_Func_Args_Ctrl_LBDrag too. maybe better to stay with engine type

2021-04-28 10:42 UTC, dedmen commented on src/client/headers/client/sqf/ai.hpp
> +            WEAPONAIM,     // Disabled weapon aiming.
is this correct enum value really?

2021-04-28 10:43 UTC, dedmen commented on src/client/headers/client/sqf/ai.hpp
> +            WEAPONAIM,     // Disabled weapon aiming.
No its not, but we also don't care I think.

2021-04-28 10:44 UTC, dedmen commented on src/client/headers/client/sqf/core.hpp
> +            std::string modname{};
sqf string type

2021-04-28 10:46 UTC, dedmen commented on src/client/headers/client/sqf/core.hpp
> +            sqf_return_string appID;    // - actual steam item ID or "0" for none or "-1" for unknown
Is the type used in structs really sqf_return_string? the return one?
Isn't that only specifically for returned values?

are there other structs wuth strings? what do they use.

2021-04-28 10:46 UTC, dedmen commented on src/client/headers/client/sqf/core.hpp
> +            sqf_return_string appID;    // - actual steam item ID or "0" for none or "-1" for unknown
https://github.com/intercept/intercept/blob/fd16da9ff8b4b890d51af7c94b86f8804e7b4460/src/client/headers/shared/client_types.hpp#L131

sqf_string.
use sqf_string when storing strings in structs

2021-04-28 10:47 UTC, dedmen commented on src/client/headers/client/sqf/debug.hpp
> +        void diag_enable(debug_toggles mode_, bool enable_);
I'm not sure if we want to support diag-binary only commands..
I think we don't. People will try to call these while running non-diag, and probably get crashes because these commands don't exist.

2021-04-28 10:52 UTC, dedmen commented on src/client/headers/client/sqf/units.hpp
> +        struct rv_zeroing {
its defined in this file, but not used here?

2021-04-28 10:53 UTC, dedmen commented on src/client/headers/client/sqf_pointers_declaration.hpp
> +//Exported Pointer Definitions For: Arma 3 205.147535 - Diag
Yeah better stay on profile, not diag only commands

2021-04-28 10:56 UTC, dedmen commented on src/client/intercept/client/sqf/core.cpp
>              return host::functions.invoke_raw_unary(__sqf::unary__isnull__script__ret__bool, test_);
lol wtf is this :D

2021-04-28 10:57 UTC, dedmen commented on src/client/intercept/client/sqf/debug.cpp
> +        void diag_dump_script_assembly(const code& code_) {
returns string. But should be removed as all the other diag commands

2021-04-28 10:58 UTC, dedmen commented on src/client/intercept/client/sqf/intersects.cpp
> +        intersect_surfaces_list line_intersects_surfaces(const vector3 &begin_pos_asl_, const vector3 &end_pos_asl_, const object &ignore_obj1_, const object &ignore_obj2_, bool sort_mode_, int max_r
maybe default =false?

2021-04-28 10:59 UTC, dedmen commented on src/client/intercept/client/sqf/vehicles.cpp
> +        #define RETURN_PYLON_MAGS if (game_return.is_empty()) return sqf_return_string_list(); \
Seems fine, if you tested it to be working

2021-04-28 11:00 UTC, dedmen requested changes
See comments

2021-04-28 16:10 UTC, Leopard20 commented on src/client/intercept/client/sqf/intersects.cpp
> +        intersect_surfaces_list line_intersects_surfaces(const vector3 &begin_pos_asl_, const vector3 &end_pos_asl_, const object &ignore_obj1_, const object &ignore_obj2_, bool sort_mode_, int max_r
It already exists in the declaration in .hpp. isn't that enough?

2021-04-28 16:11 UTC, Leopard20 commented on src/client/intercept/client/sqf/debug.cpp
> +        void diag_dump_script_assembly(const code& code_) {
meh I just added them for completeness

2021-04-28 16:11 UTC, Leopard20 commented on src/client/intercept/client/sqf/core.cpp
>              return host::functions.invoke_raw_unary(__sqf::unary__isnull__script__ret__bool, test_);
did I add that?!

2021-04-28 16:14 UTC, Leopard20 commented on src/client/headers/client/sqf/core.hpp
> +            sqf_return_string appID;    // - actual steam item ID or "0" for none or "-1" for unknown
roger

2021-04-28 16:14 UTC, Leopard20 commented on src/client/headers/client/sqf/core.hpp
> +            std::string modname{};
sure

2021-04-28 16:14 UTC, Leopard20 commented on src/client/headers/client/sqf/ai.hpp
> +            WEAPONAIM,     // Disabled weapon aiming.
I use them later in a switch and convert them to string view

2021-04-28 16:27 UTC, Leopard20 commented on src/client/headers/client/sqf/units.hpp
> +        struct rv_zeroing {
shoot! I forgot to add the declaration! :D
it's used in units.cpp

2021-04-28 16:31 UTC, Leopard20 commented on src/client/headers/client/eventhandlers.hpp
> +        types::r_string text_lb{};
should I do this for all classes/structs that I added?

2021-04-28 16:34 UTC, Leopard20 commented on src/client/intercept/client/sqf/core.cpp
>              return host::functions.invoke_raw_unary(__sqf::unary__isnull__script__ret__bool, test_);
I didn't xD

2021-04-28 22:25 UTC, Leopard20 commented
I think it should be ok now.

2021-05-01 17:03 UTC, dedmen commented
diag commands also make it harder for others to update the pointer list, because that means only people who run diag binary can generate the list

2021-05-01 17:12 UTC, dedmen requested changes

2021-05-01 17:12 UTC, dedmen commented on CMakeSettings.json
> +﻿{
This is a local only file, it shouldn't be here

2021-05-01 17:12 UTC, dedmen commented on src/client/headers/client/eventhandlers.hpp
> +        types::r_string text_lb{};
probably not. Here it makes sense, others it might not

2021-05-01 17:12 UTC, dedmen commented on src/client/headers/client/sqf/units.hpp
> +        struct rv_zeroing {
doesn't need to be in header if its not visible to anyone besides units.cpp

2021-05-01 17:12 UTC, dedmen commented on src/client/headers/shared/vector.hpp
> +            constexpr T cos(const vector3_base& v) const noexcept { T m = magnitude() * v.magnitude(); if (m == 0.0f) return 0.0f; return dot(v) / m; }
Weren't these done in that other commit that was already merged?

2021-05-01 17:12 UTC, dedmen commented on src/client/intercept/client/sqf/debug.cpp
> +        void diag_dump_script_assembly(const code& code_) {
Well either have them correct, or remove them.
I'm still for removing them as calling them won't work for the majority of users.

2021-05-01 17:12 UTC, dedmen commented on src/client/intercept/client/sqf/intersects.cpp
> +        intersect_surfaces_list line_intersects_surfaces(const vector3 &begin_pos_asl_, const vector3 &end_pos_asl_, const object &ignore_obj1_, const object &ignore_obj2_, bool sort_mode_, int max_r
ah it is yes

2021-05-01 17:12 UTC, dedmen commented on src/client/intercept/client/sqf/misc.cpp
> +
??

2021-05-01 17:12 UTC, Leopard20 commented on CMakeSettings.json
> +﻿{
I pushed it by mistake :(

2021-05-01 17:20 UTC, Leopard20 commented on src/client/intercept/client/sqf/misc.cpp
> +
I'd added something then moved it to another file. I'll remove it

2021-05-01 17:22 UTC, Leopard20 commented on src/client/headers/shared/vector.hpp
> +            constexpr T cos(const vector3_base& v) const noexcept { T m = magnitude() * v.magnitude(); if (m == 0.0f) return 0.0f; return dot(v) / m; }
wait, when did I add this?

2021-05-01 17:49 UTC, Leopard20 commented on src/client/intercept/client/sqf/debug.cpp
> +        void diag_dump_script_assembly(const code& code_) {
> work for the majority of users.

Well, not everyone uses the profiling build either. I'll remove some completely useless ones tho.

2021-05-01 18:43 UTC, Leopard20 commented
Let me re-create this branch. It was too messy.

2021-05-01 18:43 UTC, closed without merging