Add new commands from v2.05.147661; Fix broken commands
intercept/intercept pull request #254
Opened 2021-06-01 16:44 UTC by Leopard20

* Added some new commands
* Fixed a couple of broken commands

@dedmen could you review the change to common_types.hpp please?

2021-06-03 09:28 UTC, dedmen requested changes

2021-06-03 09:28 UTC, dedmen commented on src/client/headers/client/sqf/ctrl.hpp
> +        vector3 map_center_on_camera(const control &main_map, bool enable_);
What is this change?
mainmap mapCenterOnCamera enable
returns Nothing, which is void
https://community.bistudio.com/wiki/mapCenterOnCamera

2021-06-03 09:28 UTC, dedmen commented on src/client/headers/client/sqf/vehicles.hpp
> +            sqf_string LODname;  // String - LOD description name for LOD identification
```suggestion
            sqf_string lod_name;  // String - LOD description name for LOD identification
```

2021-06-03 09:28 UTC, dedmen commented on src/client/headers/client/sqf/vehicles.hpp
> +            float LODindex;  // Number - direct index of the LOD for fast access
```suggestion
            float lod_index;  // Number - direct index of the LOD for fast access
```

2021-06-03 09:28 UTC, dedmen commented on src/client/headers/client/sqf/vehicles.hpp
> +            float LODresolution;// Number - the actual LOD resolution, could be used to select LOD in selectionNames and selectionPosition
```suggestion
            float lod_resolution;// Number - the actual LOD resolution, could be used to select LOD in selectionNames and selectionPosition
```

2021-06-03 09:28 UTC, dedmen commented on src/client/headers/client/sqf/vehicles.hpp
> +        struct rv_cruise_params {
why make a struct if you can just return a std::pair<float, bool>

2021-06-03 09:28 UTC, dedmen commented on src/client/headers/client/sqf/vehicles.hpp
> +            bool cruise_enabled{};
In the set_cruise_control you named it auto_thrust, now its named cruise_enabled.
Its auto_thrust for both

2021-06-03 09:28 UTC, dedmen commented on src/client/intercept/client/sqf/ctrl.cpp
> +            return host::functions.invoke_raw_binary(__sqf::binary__mapcenteroncamera__control__bool__ret__array, main_map_, enable_);
This is wrong.
binary mapCenterOnCamera doesn't return array.

2021-06-03 09:28 UTC, dedmen commented on src/client/intercept/client/sqf/position.cpp
> +                case 0: params_right.emplace_back(std::get<0>(position_).get()); break;
why remove the std::move? shouldn't that stay?

2021-06-03 10:14 UTC, Leopard20 commented on src/client/headers/client/sqf/ctrl.hpp
> +        vector3 map_center_on_camera(const control &main_map, bool enable_);
It says it returns array (it was changed recently). I didn't actually test it to make sure.

2021-06-03 10:15 UTC, Leopard20 commented on src/client/headers/client/sqf/vehicles.hpp
> +            float LODresolution;// Number - the actual LOD resolution, could be used to select LOD in selectionNames and selectionPosition
sorry, copy pasted from the wiki :(

2021-06-03 10:16 UTC, Leopard20 commented on src/client/headers/client/sqf/vehicles.hpp
> +        struct rv_cruise_params {
I figured it'd be more readable (because you can tell what each param is without looking it up)

2021-06-03 10:17 UTC, Leopard20 commented on src/client/intercept/client/sqf/ctrl.cpp
> +            return host::functions.invoke_raw_binary(__sqf::binary__mapcenteroncamera__control__bool__ret__array, main_map_, enable_);
I will test it in the game (not sure why it was changed if it doesn't tho)

2021-06-03 10:17 UTC, Leopard20 commented on src/client/intercept/client/sqf/position.cpp
> +                case 0: params_right.emplace_back(std::get<0>(position_).get()); break;
can we use std::move on const variables?

2021-06-15 15:39 UTC, dedmen commented on src/client/headers/client/sqf/ctrl.hpp
> +        vector3 map_center_on_camera(const control &main_map, bool enable_);
I don't know why it was changed, its wrong it doesn't return array 🤷

2021-06-15 15:41 UTC, dedmen commented on src/client/intercept/client/sqf/position.cpp
> +                case 0: params_right.emplace_back(std::get<0>(position_).get()); break;
Ah they are const references... atleast two of the 3...
oof what a mess...

2021-06-15 15:42 UTC, dedmen approved these changes

2021-06-15 19:08 UTC, merged