linux_x64: Fix sizings, build, and game-state finding
intercept/intercept pull request #262
Opened 2021-12-29 19:07 UTC by mcoffin

This fixes the operability of using intercept on 64-bit linux.

* A few things were different sizes
* the layout of the partial gamestate struct used to find the gamestate pointer was incorrect
* removed unnecessary forcing of compiler options (like `-std`) in places where it doesn't make sense in favor of [`CMAKE_CXX_STANDARD`](https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_STANDARD.html)
* Use `add_compile_definitions` instead of compiler-implementation-specific define flags
* Fix the linux implementation of `IsBadReadPtr`

The IsBadReadPtr impl works as follows: on Linux, the `write()` implementation for `/dev/random` will *not* segfault when attempting to read a bad pointer. Instead, it will set `errno` to `EACCESS`. We can use this to test the validity of pointers. The previous implementation just did not work at all, and reported that all pointers were valid. I'm not sure that this behavior is necessarily guaranteed by the specification, but reading online showed that others are using it frequently for this purpose as well, so any patch to the kernel that would break this is *highly* unlikely to ever be merged due to breaking userspace usages.

I can confirm that on both 64-bit Windows and 64-bit Linux that this branch is working properly for me at the moment, but I have *not* tested 32-bit compatibility, so if someone would help test that before we lick a stamp and send it, that would be nice :)

I also moved `spdlog` here to `system` to make it easier to use different versions of `spdlog`. This is necessary for running in tandem with `extDB3` during transition periods to avoid segfaults due to differing signatures for spdlog functions. See [`mcoffin-upstream-local`](https://github.com/mcoffin/intercept/tree/mcoffin-upstream-local) for `spdlog` from our currently-utilized `extDB3`. There is also a cmake option (`USE_SYSTEM_SPDLOG`) to use the *system*'s spdlog (`/usr/include`, etc.), but people aren't likely to do this due to some packages not shipping the bundled `fmt` implementation, causing missing includes. Nevertheless, having the option present for using versions of `spdlog` that still have `#include <header.h>` style include directives is a nice feature for those who want to easily drop in their own implementation

Maintaining and rebasing this is obviously not *super* ideal, so if this could actually get upstreamed at some point I think it would be a boon for both me and others running linux dedicated servers.

2021-12-29 19:10 UTC, mcoffin commented
While the `intercept-database` side is not ready yet, for those interested, my progress branch is [here](https://github.com/mcoffin/intercept-database/tree/mcoffin). You'll just need to symlink `intercept` to this branch instead of using the included submodule, and fix the hard-coded `-m32 -march=blahblah` stuff in the other submodule-ized dependencies.

2022-04-23 16:28 UTC, Leopard20 commented on src/client/headers/client/sqf/world.hpp
> +                bool dropColorStrong_) : rainDropTexture(static_cast<std::string_view>(rainDropTexture_)),
Why was this changed? I don't see any reason for casting it to a string_view.
It has to be stored as a string anyway. So using string_view provides no advantage over const string& as far as I see.

2022-04-23 16:28 UTC, Leopard20 commented on src/client/CMakeLists.txt
> +    add_compile_options("-fPIC" "-fpermissive")
Shouldn't -O2 be kept? Or is it the default compile optimization? I don't use gcc or clang so idk.

2022-04-23 17:55 UTC, dedmen requested changes

2022-04-23 17:55 UTC, dedmen commented on src/host/invoker/invoker.cpp
> +        // _intercept_registerTypes_function.clear(); //#TEST
why?

2022-04-23 17:55 UTC, dedmen commented on src/host/intercept_dll/CMakeLists.txt
> -		"-static"
why?

2022-04-23 17:55 UTC, dedmen commented on src/host/extensions/search.cpp
> +            std::cerr << "intercept::host::extensions: searching path: " << test_path << std::endl;
Debug logging shouldn't be enabled in release builds

2022-04-23 17:55 UTC, dedmen commented on .gitignore
> +/intercept_core.pbo
Pbo's are built inside rv/addons folder (the exclude for that is already above), shouldn't need to do this

2022-04-23 17:55 UTC, dedmen commented on src/client/CMakeLists.txt
> +    add_compile_options("-fPIC" "-fpermissive")
We want to keep -s in release builds. And I don't see why you would remove O2?

2022-04-23 17:55 UTC, dedmen commented on src/host/loader/loader.cpp
> +        struct gamestate_array<uintptr_t> types;
count/capacity types are definitely in.
But due to engine layout being

struct X1 {
void* data;
int size
}

struct array : X1 {
int capacity
}


it may add padding between them? But they are definitely `int`

With padding there may be random data in the upper 32bits which might fail the equals check

Types is just auto_array

functions/operators/nulars are https://github.com/intercept/intercept/blob/fd16da9ff8b4b890d51af7c94b86f8804e7b4460/src/client/headers/shared/containers.hpp#L1705
Which is very much definitely int, not uintptr_t

2022-04-23 17:55 UTC, dedmen commented on src/host/loader/ptraccess.cpp
> +	TmpFd(const char *path, int mode):
This uses tabs.
Intercept uses 4-space indent

2022-04-23 18:01 UTC, dedmen commented on src/host/loader/loader.cpp
> +            return capacity >= count;
At this point, all of them should have equal capacity/count

2022-05-18 13:01 UTC, mcoffin commented on src/client/headers/client/sqf/world.hpp
> +                bool dropColorStrong_) : rainDropTexture(static_cast<std::string_view>(rainDropTexture_)),
This was due to an ambiguity the GCC/Clang don't like in terms of choosing which variant of the constructor to use. Since the `string_view` is constructible from whatever `rainDropTexture_` was, some compilers complain that they can't choose which overloaded version of the constructor to use. If it's better to cast to `const string&` though, then we can do that as well.

2022-05-18 13:09 UTC, mcoffin commented on src/client/CMakeLists.txt
> +    add_compile_options("-fPIC" "-fpermissive")
In this case, `-O2` was being added to *all* builds, including debug builds, as it was being added to the global `CMAKE_CXX_FLAGS`. By default, when using the proper `-DCMAKE_BUILD_TYPE=Release` flag to configure a release build, `cmake` will use `-O3` by default.

Unless the intent was to keep `-O2` for *all* builds, in which case I can just re-add it?

For reference, with `-DCMAKE_BUILD_TYPE=Release`, here's an example of one of the compilation commands that resulted (with the current CMakeLists.txt from this branch).

```
[50/58] /usr/bin/c++ -DDEVEL -DINTERCEPT_HOST_DLL=1 -DNOMINMAX -D_LINUX64=1 -D_STATIC -I/home/mcoffin/projects/intercept/build-release2/src/host/extensions -I/home/mcoffin/projects/intercept/src/host/extensions -I/home/mcoffin/projects/intercept/src/host/common -I/home/mcoffin/projects/intercept/src/host/controller
 -I/home/mcoffin/projects/intercept/src/host/loader -I/home/mcoffin/projects/intercept/src/host/invoker -I/home/mcoffin/projects/intercept/src/host/../client/headers -I/home/mcoffin/projects/intercept/src/host/intercept_dll -I/home/mcoffin/projects/intercept/src/host/common/system -I/home/mcoffin/projects/intercept
/build-release2/src/host/common -I/home/mcoffin/projects/intercept/build-release2/src/host/controller -I/home/mcoffin/projects/intercept/build-release2/src/host/loader -I/home/mcoffin/projects/intercept/build-release2/src/host/invoker -I/home/mcoffin/projects/intercept/build-release2/src/host/intercept_dll -Wno-att
ributes -O3 -DNDEBUG -fPIC -std=c++17 -MD -MT src/host/extensions/CMakeFiles/extensions_static.dir/extensions.cpp.o -MF src/host/extensions/CMakeFiles/extensions_static.dir/extensions.cpp.o.d -o src/host/extensions/CMakeFiles/extensions_static.dir/extensions.cpp.o -c /home/mcoffin/projects/intercept/src/host/extens
ions/extensions.cpp
```

So, it looks like `cmake` by default will add `-DNDEBUG -O3` for the release build type.

Either way, we shouldn't be setting release-specific flags via `CMAKE_CXX_FLAGS`, and instead `CMAKE_CXX_FLAGS_RELEASE`, or conditionals as is done with the target-specific flags below.

2022-05-18 13:09 UTC, mcoffin commented on src/host/invoker/invoker.cpp
> +        // _intercept_registerTypes_function.clear(); //#TEST
Forgot to un-comment after testing. Good catch will update.

2022-05-18 13:16 UTC, mcoffin commented on src/host/loader/loader.cpp
> +        struct gamestate_array<uintptr_t> types;
```cpp
            struct size_check {
                uintptr_t p1;//typearray
                uintptr_t typeCount;
                uintptr_t typeCapacity;
                uintptr_t p2;//functions
                int f_tableCount{ 0 };
                int f_count{ 0 };
                uintptr_t p3;//operators
                int o_tableCount{ 0 };
                int o_count{ 0 };
                uintptr_t p4;//nulars
                int n_tableCount{ 0 };
                int n_count{ 0 };
            };
```
snipped for reference ^

2022-05-18 13:17 UTC, mcoffin commented on src/host/loader/loader.cpp
> +            return capacity >= count;
Ah, so these are all guaranteed to be compact arrays, gotcha. Will update. :+1:

2022-05-18 13:29 UTC, mcoffin commented on src/host/loader/ptraccess.cpp
> +	TmpFd(const char *path, int mode):
:+1:

2022-05-18 13:39 UTC, mcoffin commented on src/client/headers/client/sqf/world.hpp
> +                bool dropColorStrong_) : rainDropTexture(static_cast<std::string_view>(rainDropTexture_)),
Actually, it appears from my commit log that this was actually MSVC that was complaining about the ambiguity in which overloaded version of the constructor to use.

2022-05-18 13:40 UTC, mcoffin commented on src/host/loader/loader.cpp
> +        struct gamestate_array<uintptr_t> types;
as long as you think that the new logic is the "more correct" one, we can for sure just remove the templated type and move it all over, I was just minimizing risk of breaking someone else's build in case I had a misunderstanding

2022-05-18 14:06 UTC, mcoffin commented on src/host/loader/loader.cpp
> +            return capacity >= count;
This was *not* the case for me locally (default branch `x64` linux), so we likely still have some typing issues with maybe garbage data in higher bits somewhere as mentioned above. I'll start looking in to it.

2022-06-23 13:31 UTC, dedmen commented on src/host/intercept_dll/CMakeLists.txt
> -		"-static"
If something seems to make no difference, I would prefer to leave it as it was

2022-06-23 13:33 UTC, dedmen commented on src/host/loader/loader.cpp
> +            return capacity >= count;
Engine calls Compact on these, after commands were added, Which should ensure that capacity==count.

2022-08-14 18:07 UTC, John-H-Smith commented
What is blocking right now?
Feature highly appreciated!

2022-08-20 16:37 UTC, dedmen commented
> What is blocking right now?
The open comments

2022-08-20 16:39 UTC, dedmen commented on src/client/headers/client/sqf/world.hpp
> +                bool dropColorStrong_) : rainDropTexture(static_cast<std::string_view>(rainDropTexture_)),
You are also breaking the sqf_string passing here.
Instead of being able to pass the string directly, you are forcing a conversion to string view and a copy. Thats not nice.
This really sohuldn't be needed

2022-08-20 16:44 UTC, dedmen commented on src/host/loader/loader.cpp
> +        struct gamestate_array<uintptr_t> types;
If this was wrong, and your uintptr_t were correct, then 
https://github.com/intercept/intercept/blob/6a5a4a914c9a82f2e5e2bc2876185fccafc4a638/src/client/headers/shared/containers.hpp#L1703
would also be wrong

2023-07-07 17:48 UTC, dedmen commented on src/host/loader/loader.cpp
> +        struct gamestate_array<uintptr_t> types;
![devenv_2023-07-07_19-48-05](https://github.com/intercept/intercept/assets/3768165/f5fc7b1c-3553-4437-bacc-552b914d24f5)
Yeah your code was wrong, unless you want to say that A3 only has 127 functions/operators

2023-07-07 18:05 UTC, dedmen commented on src/host/loader/loader.cpp
> +        struct gamestate_array<uintptr_t> types;
Actually I didn't realize how messed up this was, functions, operators, nulars. Aren't arrays at all

2023-07-07 18:12 UTC, merged