Added support for hashmap type
intercept/intercept pull request #275
Opened 2023-02-23 00:53 UTC by Leopard20

Currently this only adds `game_data_hashmap`. We also need a native implementation of unordered_map.

2023-02-23 01:41 UTC, killerswin2 commented on src/client/headers/shared/types.hpp
> +//#pragma optimize("ts", on)
#pragma optimize( "ts", on ) is equivalent to /O.

2023-02-23 09:51 UTC, dedmen requested changes

2023-02-23 09:51 UTC, dedmen commented on src/client/headers/shared/client_types.hpp
> -            obj_type_land_decal = 32
Unrelated change to hashmap, separate PR

2023-02-23 09:51 UTC, dedmen commented on src/client/headers/shared/containers.hpp
> +        const Type& get(T&& key_) const {
Should get key type from traits.
Though only argument I can think of is compilation speedup because fewer template methods, and better syntax autocomplete info thing when writing code.
Because here it doesn't know what type you could pass in.

2023-02-23 09:51 UTC, dedmen commented on src/client/headers/shared/containers.hpp
>              const int hashed_key = hash_key(key_);
if you want to do perfect forwarding, then you're missing the std::forward here

2023-02-23 09:51 UTC, dedmen commented on src/client/headers/shared/types.hpp
> +            HASHMAP,
Shouldn't this be at the bottom? instead of adding a new thing randomly in the middle?

2023-02-23 09:51 UTC, dedmen commented on src/client/headers/shared/types.hpp
> +//#pragma optimize("ts", on)
Unrelated change, shouldn't be in this PR

2023-02-23 09:51 UTC, dedmen commented on src/client/headers/shared/types.hpp
> +//#pragma optimize("ts", on)
unrelated change

2023-02-23 09:51 UTC, dedmen commented on src/client/headers/shared/types.hpp
> +            inline bool empty() const { return data.empty(); }
Instead of reimplementing all of this.
just make to_hashmap return the actual hashmap instead of the game data
So users have direct access to the actual hashmap

2023-02-23 09:51 UTC, dedmen commented on src/client/headers/shared/types.hpp
> +            return x.data->get_hash();
data might be nullptr
Better to implement a hash/get_hash method in game_value and handle it there

2023-02-23 12:16 UTC, Leopard20 commented on src/client/headers/shared/types.hpp
> +//#pragma optimize("ts", on)
uh I forgot these! It was because I'm using the Struct Layout extension and it uses Clang for compilation, and Clang just freaks about about that pragma saying it should be defined in file-scope...

2023-02-23 12:18 UTC, Leopard20 commented on src/client/headers/shared/types.hpp
> +            inline bool empty() const { return data.empty(); }
Yeah that's a better idea...

2023-02-23 12:18 UTC, Leopard20 commented on src/client/headers/shared/types.hpp
> +            return x.data->get_hash();
right didn't notice that. will do

2023-02-23 12:19 UTC, Leopard20 commented on src/client/headers/shared/types.hpp
> +//#pragma optimize("ts", on)
I didn't mean to remove these. But I'll wrap them in a `#ifdef __clang__` in another PR

2023-02-23 20:41 UTC, dedmen commented on src/client/headers/client/sqf/common_helpers.hpp
> +/*!
UTF8 bom header?

2023-02-23 20:43 UTC, dedmen commented on src/client/headers/shared/containers.hpp
> +                if (Traits::compare_keys(item.get_map_key(), key)) {
did it always return bool? as the old code was ==0?

2023-02-23 20:43 UTC, Leopard20 commented on src/client/headers/client/sqf/common_helpers.hpp
> +/*!
visual studio added that 😓

2023-02-23 20:45 UTC, Leopard20 commented on src/client/headers/shared/containers.hpp
> +                if (Traits::compare_keys(item.get_map_key(), key)) {
yeah. you must've confused it with `k1.compare(k2) == 0` in here:
```cpp
static bool compare_keys(std::string_view k1, std::string_view k2) noexcept {
            if (k1.length() != k2.length()) return false;
            return k1.compare(k2) == 0;
        }
        ```

2023-02-23 20:46 UTC, Leopard20 commented on src/client/headers/shared/containers.hpp
> +                if (Traits::compare_keys(item.get_map_key(), key)) {
everywhere else it is also just `compare_keys` as bool:
```cpp
if (Traits::compare_keys(item.get_map_key(), key_))
```

2023-02-23 20:51 UTC, Leopard20 commented on src/client/headers/client/sqf/common_helpers.hpp
> +/*!
but I guess that's harmless right?

2023-02-23 20:54 UTC, dedmen commented on src/client/headers/shared/containers.hpp
> +            rebuild(newTable);
```suggestion
        void reserve(int newTableCount) {
            if (newTableCount <= _tableCount)
                return;

            rebuild(newTableCount);
```

2023-02-23 20:54 UTC, dedmen commented on src/client/headers/shared/containers.hpp
> +            rebuild(newTable);
Also, reserve is usually for number of elements, not number of tables.
But we don't actually implement expansion factor at all so...... eh..? 

Either keep this, or make it number of entries and calculate like.. one table per 10 entries or smth..
But we'd want it log scale and.. ugh

2023-02-23 20:54 UTC, dedmen commented on src/client/headers/shared/containers.hpp
> +        Type& emplace(Args&&...args_) {
```suggestion
        template<class... Args>
        Type& emplace(Args&&... args_) {
```

2023-02-23 20:54 UTC, dedmen commented on src/client/headers/shared/containers.hpp
> +            if (this->is_null(temp))
is null can be static.
also shouldn't need `this->`?

2023-02-23 20:54 UTC, dedmen commented on src/client/headers/shared/containers.hpp
> +            if (this->is_null(temp))
yeah why the this-> everywhere?

2023-02-23 20:54 UTC, dedmen commented on src/client/headers/shared/types.hpp
> +            HASHMAP,
So its my fault then :D

2023-02-23 20:54 UTC, dedmen commented on src/client/headers/shared/types.hpp
> +            size_t hash() const { return this->get_hash(); }
```suggestion
            [[deprecated("Use get_hash instead")]] size_t hash() const { return this->get_hash(); }
```

2023-02-23 20:54 UTC, dedmen commented on src/client/headers/shared/types.hpp
>              size_t hash() const {
```suggestion
            [[deprecated("Use get_hash instead")]] size_t hash() const {
```

2023-02-23 20:54 UTC, dedmen commented on src/client/headers/shared/types.hpp
> +            size_t hash() const { return this->get_hash(); }
```suggestion
            [[deprecated("Use get_hash instead")]] size_t hash() const { return this->get_hash(); }
```

2023-02-23 20:54 UTC, dedmen commented on src/client/headers/shared/types.hpp
> +            size_t hash() const { return this->get_hash(); }
```suggestion
            [[deprecated("Use get_hash instead")]] size_t hash() const { return this->get_hash(); }
```

2023-02-23 20:54 UTC, dedmen commented on src/client/headers/shared/types.hpp
> +            size_t hash() const { return this->get_hash(); }
```suggestion
            [[deprecated("Use get_hash instead")]] size_t hash() const { return this->get_hash(); }
```

2023-02-23 20:54 UTC, dedmen commented on src/client/headers/shared/types.hpp
> +            size_t hash() const { return this->get_hash(); }
```suggestion
            [[deprecated("Use get_hash instead")]] size_t hash() const { return this->get_hash(); }
```

2023-02-23 20:54 UTC, dedmen commented on src/client/headers/shared/types.hpp
> +            size_t hash() const { return this->get_hash(); }
```suggestion
            [[deprecated("Use get_hash instead")]] size_t hash() const { return this->get_hash(); }
```

2023-02-23 20:54 UTC, dedmen commented on src/client/headers/shared/types.hpp
> +            size_t hash() const { return this->get_hash(); }
```suggestion
            [[deprecated("Use get_hash instead")]] size_t hash() const { return this->get_hash(); }
```

2023-02-23 20:54 UTC, dedmen commented on src/client/headers/shared/types.hpp
> +            size_t hash() const { return this->get_hash(); }
```suggestion
           [[deprecated("Use get_hash instead")]]  size_t hash() const { return this->get_hash(); }
```


Actually now after making all these suggestions.
You can just plainly remove all these, and add

`[[deprecated("Use get_hash instead")]]  size_t hash() const { return this->get_hash(); }`
directly into game_data instead

2023-02-23 20:54 UTC, dedmen commented on src/client/intercept/shared/types.cpp
> +                return 0;
empty fnv-1a hash is not zero, but... doesn't matter

2023-02-23 20:54 UTC, dedmen commented on src/client/intercept/shared/types.cpp
> +        size_t game_value::hash() const {
If its just a copy for back compat, could make it deprecated. but doesn't matter, probably wouldn't bother

2023-02-23 20:56 UTC, Leopard20 commented on src/client/headers/shared/types.hpp
> +            size_t hash() const { return this->get_hash(); }
Yeah idk what I was thinking 😅

2023-02-23 20:57 UTC, Leopard20 commented on src/client/headers/shared/containers.hpp
> +            if (this->is_null(temp))
visual studio was complaining can't find `get`, etc. when I was compiling. doing that fixed it 🤷‍♂️

2023-02-23 20:58 UTC, dedmen commented on src/client/headers/shared/containers.hpp
> +                if (Traits::compare_keys(item.get_map_key(), key)) {
It was compare returning number before, but I recently changed it in RV.
Guess I had the same idea back then with intercept.
but...
if it was ==0 before, then that was basically a not so the old logic was inveretd and wrong? :D 
oof, sad

2023-02-23 20:59 UTC, dedmen commented on src/client/headers/client/sqf/common_helpers.hpp
> +/*!
In many projects, the most changed line is the first, because people kepe back and forth'ing the bom mark :D 
Doesn't matter-ish

Also I can't see if it was wrong before and you fixed it, or if it was right before and you broke it :D

2023-02-23 21:24 UTC, Leopard20 commented on src/client/headers/shared/containers.hpp
> +                if (Traits::compare_keys(item.get_map_key(), key)) {
yup you were removing non-matching keys :D

2023-02-23 21:36 UTC, Leopard20 commented on src/client/headers/shared/containers.hpp
> +            rebuild(newTable);
expansion factor seems to be 16 I guess?

2023-02-24 11:57 UTC, Leopard20 commented on src/client/headers/client/sqf/common_helpers.hpp
> +/*!
Looks like it was wrong before and visual studio fixed it by itself 😅

2023-02-24 13:43 UTC, merged