Create callstack_item_data class, for helping place items on the call stack
intercept/intercept pull request #287
Opened 2023-07-05 18:19 UTC by killerswin2

creates callstack_item_data class. Moves VM_Context to the end of the file as the containter classes need the full type information else they static assert as failures.

2023-07-07 17:32 UTC, dedmen commented
Maybe we should block new/delete on it. To indicate that you shouldn't create a instance of it.
Because it veeery likely won't work right with all the missing stuff

2023-07-07 19:02 UTC, killerswin2 commented
https://github.com/killerswin2/hash_plugin/blob/master/src/hash.cpp#L983-L1011
https://github.com/killerswin2/hash_plugin/blob/master/src/hash.cpp#L1020-L1048
https://github.com/killerswin2/hash_plugin/blob/master/src/hash.cpp#L1084-L1178
https://github.com/killerswin2/hash_plugin/blob/master/src/hash.cpp#L1249-L1346
I was able to get it to work in a hashmap plugin I was working on. It is possible does seem like a hackish way to do it, but items and variables were getting created and return on the call stack

2023-07-08 21:23 UTC, Leopard20 requested changes

2023-07-08 21:23 UTC, Leopard20 commented on src/client/headers/shared/types.hpp
> +            {
```suggestion
            void throw_script_exception(game_value value) {
```

2023-07-08 21:23 UTC, Leopard20 commented on src/client/headers/shared/types.hpp
> +            {
The opening braces must be inline with the function declaration:
```suggestion
            auto add_callstack_item(ref<callstack_item> newItem) {
```

2023-07-08 21:23 UTC, Leopard20 commented on src/client/headers/shared/types.hpp
> +            {
```suggestion
            bool is_scheduled() const {
```

2023-07-08 21:23 UTC, Leopard20 commented on src/client/headers/shared/types.hpp
> +            {
```suggestion
            bool is_serialization_enabled() const {
```

2023-07-08 21:23 UTC, Leopard20 commented on src/client/headers/shared/types.hpp
> +            {
```suggestion
            void disable_serialization() {
```

2023-07-08 21:23 UTC, Leopard20 commented on src/client/headers/shared/types.hpp
> +            {
```suggestion
            const sourcedocpos& get_current_position() {
```

2023-07-27 18:06 UTC, merged